### ISSUE TITLE
How to add users?

### ISSUE THREAD

**Issue by RyokoAsakura** [ox/aim-oscar-server#1]
I've got the code up and running, but I have NO idea how to add users to my server. Any help here would be greatly appreciated!

**Comment by RyokoAsakura** [comment]
I've noticed that no DB migration is running as well, I believe this to be the error, but how to run migration manually?

**Comment by RyokoAsakura** [comment]
Closing issue as after much stupidity, I figured it out. :P Thanks for the nostalgia!

For those wondering, run go run main.go in the cmd/migrate folder to migrate the DBs and then you have to change the last_activity_at time stamp in the table users for each of the 2 users for them to be usable, otherwise it will kick back a time.Parser error. This command, once in the table, should fix it.` update USERS set LAST_ACTIVITY_AT = '2000-01-01 00:00:00.00000-05' where LAST_ACTIVITY_AT = '0001-12-31 19:03:58-04:56:02 BC';
`

**Comment by ox** [comment]
Hey there! So I made a buuunch of changes to this and added some actual user management scripts under `cmd/user`. Would love to hear if it works ok for you
