### ISSUE TITLE
Can't migrate DB

### ISSUE THREAD

**Issue by josephlombardo1** [ox/aim-oscar-server#14]
When i run the command provided, i get this error:

2024/03/28 20:26:19 could not parse config: field "BOS" is required but the value is not provided
exit status 1

Anyone know how to fix this?
OS: Ubuntu Jammy(idk version number)

**Comment by ukozi** [comment]
Yeah I have pull request to fix this, in the example yaml they provide change `bos_addr` to `bos`.

**Comment by josephlombardo1** [comment]
Ok thanks. I was trying to fix it on my own. What is going on is Go sees the bos address but it is under the wrong name. Thanks for the help.
