### ISSUE TITLE
macOS app does not run

### ISSUE THREAD

**Issue by GRardB** [ox/aim-oscar-server#17]
![Issues_·_ox_aim-oscar-server](https://github.com/ox/aim-oscar-server/assets/748180/77200e61-fd5b-4351-89cf-4c108d478fe3)

Is it because I don't live in America?

**Comment by mk6i** [comment]
Did you remove the quarantine flag?

```sh
xattr -d com.apple.quarantine ~/Downloads/AIM35.app
```

**Comment by GRardB** [comment]
That fixed it, thanks!
