### ISSUE TITLE
./run.sh does not start the server.

### ISSUE THREAD

**Issue by aloysiusantioch** [ox/aim-oscar-server#3]
Receiving errors when trying to use the ./run.sh. First:

```
# ./run.sh 
./run.sh: 3: .: dev.env: not found
```

Correcting this by modifying run.sh from:
`. dev.env
`
To:
`. env/dev.env`

Then:
```
# ./run.sh 
./run.sh: 4: ./aim-oscar: not found
```

Im not sure what this is supposed to be kicking off so I cant fix it myself.

**Comment by aloysiusantioch** [comment]
After building the go stuff, i found that it puts the aim-oscar built stuff into ~username/go rather than the go directory (/usr/local/go in my case.  Fixing this allowed the server to launch.

`root@server:/opt/AIM# ./run.sh 
2023/06/15 10:53:07 DB URL: server.name:5432
2023/06/15 10:53:07 message delivery routine started
OSCAR listening on 0.0.0.0:5190
OSCAR BOS set to server.name:5190
2023/06/15 10:53:07 online notification starting up`

**Comment by ox** [comment]
Hey! So I use `nodemon` to watch for changes and rebuild the service. I mainly use `npm run dev` to run that command. It's not ideal to also require npm to get things running easily but it has worked for me for now. I'll try to put up better docs on how to run this whole thing.

**Comment by ox** [comment]
@aloysiusantioch so I updated a _lot_ of the code to improve DX but also to cleanup service configuration. The new way to run the server is

- create a config.yml
- run `scripts/run.sh`

Let me know if you have trouble getting it to work now. Thanks for posting an issue!
